import {
  BadRequestException,
  Injectable,
  InternalServerErrorException,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
// Entity
import { Product } from './entities/product.entity';
// Data Transfer Object (DTO's)
import { CreateProductDto } from './dto/create-product.dto';
import { UpdateProductDto } from './dto/update-product.dto';
import { PaginationDto } from 'src/common/dtos/pagination.dto';

@Injectable()
export class ProductsService {
  private readonly logger = new Logger('ProductsService');

  constructor(
    @InjectRepository(Product) // Introducimos la entidad "Product"
    private readonly productRepository: Repository<Product>,
  ) {}

  async create(createProductDto: CreateProductDto) {
    try {
      const product = this.productRepository.create(createProductDto); // Crea la instancia
      await this.productRepository.save(product); // Guarda el product en DB

      return product;
    } catch (error) {
      this.handleDBExceptions(error);
    }
  }

  // todo: paginaci√≥n
  findAll(paginationDto: PaginationDto) {
    const { limit = 10, offset = 0 } = paginationDto;
    return this.productRepository.find({
      take: limit,
      skip: offset,
      // todo: relaciones
    });
  }

  async findOne(id: string) {
    const product = await this.productRepository.findOneBy({ id }); // Solo acepta string ü§∑üèª‚Äç‚ôÄÔ∏è

    if (!product) {
      throw new NotFoundException(`Product with ID: ${id} Not Found`);
    }

    return product;
  }

  update(id: string, updateProductDto: UpdateProductDto) {
    return `This action updates a #${id} product`;
  }

  async remove(id: string) {
    const product = await this.findOne(id);

    // No hay que comprobar si existe porque ya el m√©todo findOne ya lanza una exception si no existe

    await this.productRepository.remove(product);
  }

  private handleDBExceptions(error: any) {
    if (error.code === '23505') {
      throw new BadRequestException(error.detail);
    }
    this.logger.error(error);
    throw new InternalServerErrorException(
      'Unexpected error, check server logs',
    );
  }
}
